### ISSUE TITLE
Model streaming API enhancement

### ISSUE THREAD

**Issue by SeanHH86** [OpenCSGs/llm-inference#67]
1. Stream request load-balance for multi-workers for predictor.
2. More parameters for model.generate api
3. Stream support  for class DefaultTransformersPipeline
4. RouterDeployment api support format `"/{model}/run/predict"`
5. Model id mapping for api server, like mapping `facebook/opt-125m` to `facebook--opt-125m`

**Comment by depenglee1707** [comment]
#82

**Comment by SeanHH86** [comment]
Done
